# Generated by Django 5.1 on 2026-04-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_bank_account_number_customuser_ifsc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer')], default='upi', max_length=20),
        ),
    ]
